# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-07 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='assress',
            new_name='address',
        ),
    ]
